### ISSUE TITLE
No BOM Included

### ISSUE THREAD

**Issue by mayuragarwal2004** [kerikun11/micromouse-kerise-v4#1]
Hey, we really liked your micro mouse design, we would like to try them, for the same, we want to manufacture the board, but looks like you haven't provided the Bill of Material file required for the list of components to be soldered on the PCB board. If you could provide the same, it will help us better understand and learn about it. We would be glad to learn from your designs. 

Waiting for your reply.

Mayur Agarwal,
Support from India for your future endeavours.

**Comment by kerikun11** [comment]
@mayuragarwal2004 
Thank you for visiting KERISE v4.
KiCad can be used to generate a BOM.
I've attached an example of a generated BOM:
[KERISE.csv](https://github.com/kerikun11/micromouse-kerise-v4/files/11900721/KERISE.csv)

By the way, KERISEv4 is too complicated, so I think it would be difficult for anyone other than me to create it.
I recommend that you use KERISEv4 only as a reference and design your own new one.

**Comment by mayuragarwal2004** [comment]
Thank you for replying so fast, I found the BOM and other files. Could you also tell me what part you think will be complicated for me to make the KeriseV4?

**Comment by kerikun11** [comment]
For example this one.

[LXDC2UR30A](https://www.digikey.jp/short/fztzn435)
![image](https://github.com/kerikun11/micromouse-kerise-v4/assets/9977612/44c4a736-e105-46e3-afa6-64d77af6927e)

**Comment by mayuragarwal2004** [comment]
We are getting the pcb manufactured from my teammates father's pcb manufacturing company, that might make it easier and less complicated right?

**Comment by kerikun11** [comment]
It's fine to make it yourself, but I don't have time to support it, so please solve it yourself.  I hope you can make it successfully.

**Comment by mayuragarwal2004** [comment]
Hello once again,
I had a small question, the Antenna, AE1, is given the footprint of hidden pad, is AE1 some component to be soldered on the board? or can it be just removed from the BOM? If it is a component, could you please tell me it's name?

**Comment by kerikun11** [comment]
AE1 is not used at all.
